package com.pisey.flutter_native_player.download_hls

object ConstantDownload {
    const val ACTION_PERCENTAGE_DOWNLOADED = "ACTION_PERCENTAGE_DOWNLOADED"
    const val ACTION_STATUS_DOWNLOAD = "ACTION_STATUS_DOWNLOAD"

    const val VALUE_PERCENTAGE_DOWNLOADED = "VALUE_PERCENTAGE_DOWNLOADED"
    const val VALUE_STATUS_DOWNLOAD = "VALUE_STATUS_DOWNLOAD"

    const val DOWNLOAD_STARTED = "DOWNLOAD_STARTED"
    const val DOWNLOAD_COMPLETED = "DOWNLOAD_COMPLETED"
    const val DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    const val DOWNLOAD_CANCELED = "DOWNLOAD_CANCELED"
}