package com.pisey.flutter_native_player.download_hls

object ConstantDownload {
    const val ACTION_DOWNLOAD_PERCENTAGE = "ACTION_DOWNLOAD_PERCENTAGE"
    const val ACTION_DOWNLOAD_STATUS = "ACTION_DOWNLOAD_STATUS"
    const val DATA_DOWNLOAD_STATUS = "DATA_DOWNLOAD_STATUS"

    const val DATA_DOWNLOAD_PERCENTAGE = "DATA_DOWNLOAD_PERCENTAGE"

    const val STATE_IS_DOWNLOADED = 168

    const val DOWNLOAD_STARTED = "DOWNLOAD_STARTED"
    const val DOWNLOAD_COMPLETED = "DOWNLOAD_COMPLETED"
    const val DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    const val DOWNLOAD_CANCELED = "DOWNLOAD_CANCELED"
}