class Constant {
  static const MP_VIEW_TYPE = "player_cross_platform";

  static const METHOD_CHANNEL_PLAYER = "METHOD_CHANNEL_PLAYER";
  static const EVENT_CHANNEL_PLAYER = "EVENT_CHANNEL_PLAYER";
  static const EVENT_CHANNEL_PERCENTAGE_DOWNLOADED =
      "EVENT_CHANNEL_PERCENTAGE_DOWNLOADED";
  static const EVENT_CHANNEL_DOWNLOAD_STATUS = "EVENT_CHANNEL_DOWNLOAD_STATUS";

  static const METHOD_PLAY = "METHOD_PLAY";
  static const METHOD_PAUSE = "METHOD_PAUSE";
  static const METHOD_RESTART = "METHOD_RESTART";

  static const METHOD_GET_LIST_QUALITY_VIDEO = "METHOD_GET_QUALITY_VIDEO";
  static const METHOD_GET_DURATION_STATE = "METHOD_GET_DURATION_STATE";
  static const METHOD_SEEK_TO = "METHOD_SEEK_TO";
  static const METHOD_START_DOWNLOAD = "METHOD_START_DOWNLOAD";
  static const METHOD_CANCEL_DOWNLOAD = "METHOD_CANCEL_DOWNLOAD";
  static const METHOD_CHECK_IS_DOWNLOAD = "METHOD_CHECK_IS_DOWNLOAD";
  static const METHOD_CHANGE_QUALITY = "METHOD_CHANGE_QUALITY";
  static const METHOD_CHANGE_PLAYBACK_SPEED = "METHOD_CHANGE_PLAYBACK_SPEED";
  static const METHOD_CHANGE_SUBTITLE = "METHOD_CHANGE_SUBTITLE";
  static const METHOD_SHOW_DEVICES = "METHOD_SHOW_DEVICES";
  static const METHOD_RELEASE_PLAYER = "METHOD_RELEASE_PLAYER";
  static const METHOD_INIT_PLAYER = "METHOD_INIT_PLAYER";
  static const METHOD_IS_PLAYING = "METHOD_IS_PLAYING";

  static const KEY_WIDTH = "KEY_WIDTH";
  static const KEY_HEIGHT = "KEY_HEIGHT";
  static const KEY_BITRATE = "KEY_BITRATE";
  static const KEY_URL_QUALITY = "KEY_URL_QUALITY";

  static const KEY_PLAY_WHEN_READY = "KEY_PLAY_WHEN_READY";
  static const KEY_PLAYER_RESOURCE = "KEY_PLAYER_RESOURCE";
  static const KEY_TITLE_MOVIE = "KEY_TITLE_MOVIE";
  static const KEY_URL_MOVIE = "KEY_URL_MOVIE";
  static const KEY_SUBTITLES = "KEY_SUBTITLES";
  static const KEY_TRACK_INDEX = "KEY_TRACK_INDEX";

  static const KEY_SUBTITLE_LABEL = "KEY_SUBTITLE_LABEL";
  static const KEY_SUBTITLE_INDEX = "KEY_SUBTITLE_INDEX";

  static const KEY_CURRENT_POSITION = "KEY_CURRENT_POSITION";
  static const KEY_TOTAL_DURATION = "KEY_TOTAL_DURATION";
  static const KEY_BUFFER_UPDATE = "KEY_BUFFER_UPDATE";

  static const KEY_EVENT_TYPE = "KEY_EVENT_TYPE";
  static const KEY_VALUE_OF_EVENT = "KEY_VALUE_OF_EVENT";

  static const EVENT_PROGRESS_DOWNLOAD = "EVENT_PROGRESS_DOWNLOAD";
  static const EVENT_DOWNLOAD_QUEUED = "EVENT_DOWNLOAD_QUEUED";
  static const EVENT_DOWNLOAD_STARTED = "EVENT_DOWNLOAD_STARTED";
  static const EVENT_DOWNLOAD_PAUSED = "EVENT_DOWNLOAD_PAUSED";
  static const EVENT_DOWNLOAD_RESUMED = "EVENT_DOWNLOAD_RESUMED";
  static const EVENT_DOWNLOAD_COMPLETED = "EVENT_DOWNLOAD_COMPLETED";
  static const EVENT_DOWNLOAD_FAILED = "EVENT_DOWNLOAD_FAILED";
  static const EVENT_DOWNLOAD_CANCELED = "EVENT_DOWNLOAD_CANCELED";
  static const EVENT_DOWNLOAD_NOT_YET = "EVENT_DOWNLOAD_NOT_YET";

  static const EVENT_READY_TO_PLAY = "EVENT_READY_TO_PLAY";
  static const EVENT_PLAY = "EVENT_PLAY";
  static const EVENT_PAUSE = "EVENT_PAUSE";
  static const EVENT_LOADING = "EVENT_LOADING";
  static const EVENT_FINISH = "EVENT_FINISH";
}
