package com.pisey.flutter_native_player.constants

object Constant {

    const val MP_VIEW_TYPE = "player_cross_platform";

    const val METHOD_CHANNEL_PLAYER = "METHOD_CHANNEL_PLAYER";
    const val EVENT_CHANNEL_PLAYER = "EVENT_CHANNEL_PLAYER";
    const val EVENT_CHANNEL_PERCENTAGE_DOWNLOADED = "EVENT_CHANNEL_PERCENTAGE_DOWNLOADED";
    const val EVENT_CHANNEL_DOWNLOAD_STATUS = "EVENT_CHANNEL_DOWNLOAD_STATUS";

    const val METHOD_PLAY = "METHOD_PLAY";
    const val METHOD_PAUSE = "METHOD_PAUSE";
    const val METHOD_RESTART = "METHOD_RESTART";

    const val METHOD_GET_LIST_QUALITY_VIDEO = "METHOD_GET_QUALITY_VIDEO";
    const val METHOD_GET_DURATION_STATE = "METHOD_GET_DURATION_STATE";
    const val METHOD_SEEK_TO = "METHOD_SEEK_TO";
    const val METHOD_START_DOWNLOAD = "METHOD_START_DOWNLOAD";
    const val METHOD_CANCEL_DOWNLOAD = "METHOD_CANCEL_DOWNLOAD";
    const val METHOD_CHECK_IS_DOWNLOAD = "METHOD_CHECK_IS_DOWNLOAD";
    const val METHOD_CHANGE_QUALITY = "METHOD_CHANGE_QUALITY";
    const val METHOD_CHANGE_PLAYBACK_SPEED = "METHOD_CHANGE_PLAYBACK_SPEED";
    const val METHOD_CHANGE_SUBTITLE = "METHOD_CHANGE_SUBTITLE";
    const val METHOD_SHOW_DEVICES = "METHOD_SHOW_DEVICES"
    const val METHOD_RELEASE_PLAYER = "METHOD_RELEASE_PLAYER"
    const val METHOD_INIT_PLAYER = "METHOD_INIT_PLAYER"
    const val METHOD_IS_PLAYING = "METHOD_IS_PLAYING"

    const val KEY_WIDTH = "KEY_WIDTH";
    const val KEY_HEIGHT = "KEY_HEIGHT";
    const val KEY_BITRATE = "KEY_BITRATE";
    const val KEY_URL_QUALITY = "KEY_URL_QUALITY";

    const val KEY_PLAY_WHEN_READY = "KEY_PLAY_WHEN_READY"
    const val KEY_PLAYER_RESOURCE = "KEY_PLAYER_RESOURCE"
    const val KEY_TITLE_MOVIE = "KEY_TITLE_MOVIE";
    const val KEY_URL_MOVIE = "KEY_URL_MOVIE";
    const val KEY_SUBTITLES = "KEY_SUBTITLES"
    const val KEY_TRACK_INDEX = "KEY_TRACK_INDEX";

    const val KEY_SUBTITLE_LABEL = "KEY_SUBTITLE_LABEL";
    const val KEY_SUBTITLE_INDEX = "KEY_SUBTITLE_INDEX";

    const val KEY_CURRENT_POSITION = "KEY_CURRENT_POSITION";
    const val KEY_TOTAL_DURATION = "KEY_TOTAL_DURATION";
    const val KEY_BUFFER_UPDATE = "KEY_BUFFER_UPDATE";

    const val KEY_EVENT_TYPE = "KEY_EVENT_TYPE";
    const val KEY_VALUE_OF_EVENT = "KEY_VALUE_OF_EVENT";

    const val EVENT_PROGRESS_DOWNLOAD = "EVENT_PROGRESS_DOWNLOAD";
    const val EVENT_DOWNLOAD_QUEUED = "EVENT_DOWNLOAD_QUEUED"
    const val EVENT_DOWNLOAD_STARTED = "EVENT_DOWNLOAD_STARTED";
    const val EVENT_DOWNLOAD_PAUSED = "EVENT_DOWNLOAD_PAUSED";
    const val EVENT_DOWNLOAD_RESUMED = "EVENT_DOWNLOAD_RESUMED";
    const val EVENT_DOWNLOAD_COMPLETED = "EVENT_DOWNLOAD_COMPLETED";
    const val EVENT_DOWNLOAD_FAILED = "EVENT_DOWNLOAD_FAILED";
    const val EVENT_DOWNLOAD_CANCELED = "EVENT_DOWNLOAD_CANCELED";
    const val EVENT_DOWNLOAD_NOT_YET = "EVENT_DOWNLOAD_NOT_YET"

    const val EVENT_READY_TO_PLAY = "EVENT_READY_TO_PLAY";
    const val EVENT_PLAY = "EVENT_PLAY";
    const val EVENT_PAUSE = "EVENT_PAUSE";
    const val EVENT_LOADING = "EVENT_LOADING";
    const val EVENT_FINISH = "EVENT_FINISH";

    const val EVENT_TV_HIDE_BUTTON_CAST = "EVENT_TV_HIDE_BUTTON_CAST"
    const val EVENT_TV_SHOW_BUTTON_CAST = "EVENT_TV_SHOW_BUTTON_CAST"
    const val EVENT_TV_DISCONNECTED = "EVENT_TV_DISCONNECTED"
    const val EVENT_TV_CONNECTED = "EVENT_TV_CONNECTED"

    const val EXO_PLAYER_RESOURCE = "EXO_PLAYER_RESOURCE"
}